/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoPresentacion;

import DTO.ClienteDTO;
import javax.swing.JOptionPane;
import static proyectoPresentacion.PantallaPrincipal.c;

/**
 *
 * @author Nacho
 */
public class EditarCliente extends javax.swing.JFrame {

    ClienteDTO cliente;

    Thread t1 = new Thread() {
        public void run() {
            
            c.ConsultarUbicacion(PantallaPrincipal.argss, tfDireccion.getText());
            
        }
    };
    /**
     * Creates new form EditarCliente
     */
    public EditarCliente(ClienteDTO cliente) {
        this.cliente=cliente;
        initComponents();
    }

    private EditarCliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnVerMapa = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 567));
        setMinimumSize(new java.awt.Dimension(480, 567));
        setPreferredSize(new java.awt.Dimension(480, 567));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCliente.setPreferredSize(new java.awt.Dimension(859, 617));
        PanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ddcliente.png"))); // NOI18N
        PanelCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 370, 60));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(147, 50));
        btnEliminar.setMinimumSize(new java.awt.Dimension(147, 50));
        btnEliminar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelCliente.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnVerMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verMapa.png"))); // NOI18N
        btnVerMapa.setBorderPainted(false);
        btnVerMapa.setContentAreaFilled(false);
        btnVerMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerMapa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerMapa.setMaximumSize(new java.awt.Dimension(147, 50));
        btnVerMapa.setMinimumSize(new java.awt.Dimension(147, 50));
        btnVerMapa.setPreferredSize(new java.awt.Dimension(147, 50));
        btnVerMapa.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verMapa3.png"))); // NOI18N
        btnVerMapa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verMapa2.png"))); // NOI18N
        btnVerMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMapaActionPerformed(evt);
            }
        });
        PanelCliente.add(btnVerMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(147, 50));
        btnGuardar.setMinimumSize(new java.awt.Dimension(147, 50));
        btnGuardar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar2.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        PanelCliente.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelCliente.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 150, 50));

        tfNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNombre.setBorder(null);
        PanelCliente.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 330, 20));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nombre.png"))); // NOI18N
        PanelCliente.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        tfDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDireccion.setBorder(null);
        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });
        PanelCliente.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/direccion.png"))); // NOI18N
        PanelCliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        tfTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTelefono.setBorder(null);
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyReleased(evt);
            }
        });
        PanelCliente.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono.png"))); // NOI18N
        PanelCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jLabel34.setText("jLabel34");
        jLabel34.setMaximumSize(new java.awt.Dimension(480, 567));
        jLabel34.setMinimumSize(new java.awt.Dimension(480, 567));
        jLabel34.setPreferredSize(new java.awt.Dimension(480, 567));
        PanelCliente.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 580));

        getContentPane().add(PanelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 807, 607));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String[] opciones = {"Si", "No"};
        int ax = JOptionPane.showOptionDialog(null, "¿Está seguro?", "Eliminar", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, opciones, null);
        if (ax == JOptionPane.YES_OPTION) {
            c.eliminar(c.buscar(cliente));
            //            Contenedor.removeAll();
            //            Contenedor.add(PanelMR);
            //            Contenedor.repaint();
            //            Contenedor.revalidate();

        } else if (ax == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMapaActionPerformed
        // TODO add your handling code here:
        t1.start();
    }//GEN-LAST:event_btnVerMapaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cliente = new ClienteDTO(tfNombre.getText(), tfTelefono.getText(), tfDireccion.getText());
        c.crear(cliente);
        btnVerMapa.setEnabled(true);
        btnEliminar.setEnabled(true);

        tfNombre.setEnabled(false);
        tfDireccion.setEnabled(false);
        tfTelefono.setEnabled(false);

        btnGuardar.hide();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionActionPerformed

    private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerMapa;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
