/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoPresentacion;

import DTO.ClienteDTO;
import java.util.Observable;
import validadores_147333.Validadores;

/**
 *
 * @author amaci
 */
public class MenuRapido extends javax.swing.JPanel {

    Validadores validador = new Validadores();

    /**
     * Creates new form MenuRapido
     */
    public MenuRapido() {
        initComponents();
        btnVerificar.setEnabled(false);
        this.resize(351, 332);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(351, 332));

        jLabel1.setText("Teléfono:");

        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyReleased(evt);
            }
        });

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/verificar.png"))); // NOI18N
        btnVerificar.setBorderPainted(false);
        btnVerificar.setContentAreaFilled(false);
        btnVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerificar.setMaximumSize(new java.awt.Dimension(147, 50));
        btnVerificar.setMinimumSize(new java.awt.Dimension(147, 50));
        btnVerificar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnVerificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/verificar3.png"))); // NOI18N
        btnVerificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/verificar2.png"))); // NOI18N
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        try {

            ClienteDTO cliente = PantallaPrincipal.c.buscar(new ClienteDTO(tfTelefono.getText()));
            if (cliente.getIdCliente() != null) {
                AdminCliente ac = new AdminCliente(cliente);

                PantallaPrincipal.panel1.removeAll();
                PantallaPrincipal.panel1.add(ac);
                PantallaPrincipal.panel1.revalidate();
                PantallaPrincipal.panel1.repaint();

            }
        } catch (Exception e) {
            AdminCliente ac = new AdminCliente(tfTelefono.getText());

            PantallaPrincipal.panel1.removeAll();
            PantallaPrincipal.panel1.add(ac);
            PantallaPrincipal.panel1.revalidate();
            PantallaPrincipal.panel1.repaint();
        }


    }//GEN-LAST:event_btnVerificarActionPerformed

    private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyReleased
        if (validador.validaEnteroMaxDigitos(10, tfTelefono.getText()) && validador.validaEntero(tfTelefono.getText())) {
            btnVerificar.setEnabled(true);
        } else {
            btnVerificar.setEnabled(false);
        }


    }//GEN-LAST:event_tfTelefonoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
