/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoPresentacion;

import Control.Control;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Panel;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author amaci
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    static Control c = new Control();
    static String[] argss;
    Panel panel = new Panel();

    

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {

        initComponents();


    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        btnMenuRapido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(390, 430));
        setMinimumSize(new java.awt.Dimension(390, 430));
        setPreferredSize(new java.awt.Dimension(390, 430));

        panel1.setMaximumSize(new java.awt.Dimension(390, 430));
        panel1.setMinimumSize(new java.awt.Dimension(390, 430));
        panel1.setPreferredSize(new java.awt.Dimension(390, 430));
        panel1.setVerifyInputWhenFocusTarget(false);

        btnMenuRapido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/menuRapido.png"))); // NOI18N
        btnMenuRapido.setBorderPainted(false);
        btnMenuRapido.setContentAreaFilled(false);
        btnMenuRapido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuRapido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuRapido.setMaximumSize(new java.awt.Dimension(147, 50));
        btnMenuRapido.setMinimumSize(new java.awt.Dimension(147, 50));
        btnMenuRapido.setPreferredSize(new java.awt.Dimension(147, 50));
        btnMenuRapido.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/menuRapido3.png"))); // NOI18N
        btnMenuRapido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/menuRapido2.png"))); // NOI18N
        btnMenuRapido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuRapidoMouseEntered(evt);
            }
        });
        btnMenuRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRapidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnMenuRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnMenuRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jMenuItem1.setText("Lista de clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel1.getAccessibleContext().setAccessibleName("");
        panel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRapidoActionPerformed
        // TODO add your handling code here:
        MenuRapido mr = new MenuRapido();
        
        panel1.removeAll();

        panel1.add(mr);
        panel1.revalidate();
        panel1.repaint();
        this.resize(391, 400);
        this.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnMenuRapidoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TablaClientes tc = new TablaClientes();
        tc.setSize(449, 349);
        this.remove(panel1);
        this.add(tc);
        this.revalidate();
        this.repaint();
        this.resize(449, 349);
        this.setLocationRelativeTo(null);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnMenuRapidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuRapidoMouseEntered
            
    }//GEN-LAST:event_btnMenuRapidoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        argss = args;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuRapido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
