/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoPresentacion;

import DTO.ClienteDTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nacho
 */
public class TablaClientes extends javax.swing.JPanel {

    DefaultTableModel modelotabla;

    /**
     * Creates new form TablaClientes
     */
    public TablaClientes() {
        String[] columna = new String[]{"Nombre", "Dirección", "Teléfono"};
        modelotabla = new DefaultTableModel(null, columna);
        setFilas();
        initComponents();

    }

    public void setFilas() {
        ArrayList<ClienteDTO> lista = new ArrayList<ClienteDTO>();
        lista.addAll(PantallaPrincipal.c.listarClientes());
        System.out.println(lista.get(0));
        Object datos[] = new Object[3];
        for (int i = 0; i < lista.size(); i++) {
            datos[0] = lista.get(i).getNombre();
            datos[1] = lista.get(i).getDireccion();
            datos[2] = lista.get(i).getTelefono();
            modelotabla.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(modelotabla);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
